In [1]:
import os
import sys
from pathlib import Path

ROOT = Path(os.path.abspath('')).resolve().parents[2]
SRC = ROOT / "src"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))


import nvitk as nv
from nvitk import db
import pandas as pd

In [2]:
from nvitk.db import DataRepo, import_pesabrain_source, list_pesabrain_sources

db_base = Path("/data_local/LabVF/PESA-Brain/DB/DB")
repo = DataRepo("dataset", auto_scaffold=True)

In [3]:
pd.DataFrame(list_pesabrain_sources())

,filename,sheet,source_kind,domain,layout,modality,cohort_id,batch_id,default_visit_label
0,PESABrain_4DFlow_LocalizedPI_20260216.xlsx,PESABrain_AnalysisDB_Batch1,image_wide,image,wide,4dflow,PESA-Brain,4DFlow-Processed,4
1,PESABrain_4DFlow_LocalizedTimeAvgFlow_20260216...,PESABrain_AnalysisDB_Batch1,image_wide,image,wide,4dflow,PESA-Brain,4DFlow-Processed,4
2,PESABrain_4DFlow_LocalizedTimeseriesFlow_Wide_...,Datos,image_timeseries_wide,image,wide,4dflow,PESA-Brain,4DFlow-Processed,4
3,PESABrain_APOE_20260318.xlsx,Sheet1,clinical_wide,clinical,wide,NaN,PESA-Brain,All,4
4,PESABrain_ASLPerfusion_ThrMeanCBF_20260216.xlsx,Sheet1,image_wide,image,wide,asl,PESA-Brain,All,4
5,PESABrain_ASLPerfusion_VascularAtlas_MeanCBF_2...,Sheet1,image_wide,image,wide,asl,PESA-Brain,All,4
6,PESABrain_All_4DFlow_IDs.xlsx,Sheet1,subject_ids,metadata,wide,NaN,PESA-Brain,4DFlow-Processed,4
7,PESABrain_All_IDs.xlsx,Sheet1,subject_ids,metadata,wide,NaN,PESA-Brain,All,4
8,PESABrain_Clinical_20260216.xlsx,Sheet1,clinical_wide,clinical,wide,NaN,PESA-Brain,All,4
9,PESABrain_Clinical_AllXNAT_20260216.xlsx,Datos,clinical_wide,clinical,wide,NaN,PESA-Brain,All,4
10,PESABrain_Echography_CarotidePlaque_20260216.xlsx,Sheet1,clinical_wide,clinical,wide,NaN,PESA-Brain,All,4
11,PESABrain_SubjectCatalog_AllXNAT_20260216.xlsx,Datos,subject_catalog,metadata,wide,NaN,PESA-Brain,All,4
12,PESABrain_TAC_20260318.xlsx,Sheet1,clinical_wide,clinical,wide,NaN,PESA-Brain,All,4

In [4]:
trial_id = 'trial_ids_001'

# res = import_pesabrain_source(
#     repo,
#     db_base,
#     "PESABrain_All_IDs.xlsx",
#     sheet="Sheet1",
#     source_kind="subject_ids",
#     source_batch_id=trial_id,
# )

In [7]:
res

{'filename': 'PESABrain_All_IDs.xlsx',
 'sheet': 'Sheet1',
 'source_kind': 'subject_ids',
 'result':        subject_uid    id_namespace    id_value                  id_source  \
 0          PESA841      patient_id     PESA841  PESABrain_All_IDs::Sheet1
 1          PESA841          mri_id  BMRI290077  PESABrain_All_IDs::Sheet1
 2          PESA841            seqn          28  PESABrain_All_IDs::Sheet1
 3          PESA841     medrecon_id    RE629534  PESABrain_All_IDs::Sheet1
 4          PESA841  psicosocial_id    PS366003  PESABrain_All_IDs::Sheet1
 ...            ...             ...         ...                        ...
 5324  PESA18028516          mri_id  BMRI693925  PESABrain_All_IDs::Sheet1
 5325  PESA18028516            seqn        4245  PESABrain_All_IDs::Sheet1
 5326  PESA18028516     medrecon_id    RE666499  PESABrain_All_IDs::Sheet1
 5327  PESA18028516         fert_id    FE894940  PESABrain_All_IDs::Sheet1
 5328  PESA18028516  psicosocial_id    PS464599  PESABrain_All_IDs::Sheet1

       is_primary source_batch_id                 updated_at
 0           True   trial_ids_001  2026-04-10T15:09:37+00:00
 1          False   trial_ids_001  2026-04-10T15:09:37+00:00
 2           True   trial_ids_001  2026-04-10T15:09:37+00:00
 3          False   trial_ids_001  2026-04-10T15:09:37+00:00
 4          False   trial_ids_001  2026-04-10T15:09:37+00:00
 ...          ...             ...                        ...
 5324       False   trial_ids_001  2026-04-10T15:09:37+00:00
 5325        True   trial_ids_001  2026-04-10T15:09:37+00:00
 5326       False   trial_ids_001  2026-04-10T15:09:37+00:00
 5327       False   trial_ids_001  2026-04-10T15:09:37+00:00
 5328       False   trial_ids_001  2026-04-10T15:09:37+00:00

 [5329 rows x 7 columns],
 'subjects':        subject_uid primary_patient_id primary_seqn   sex birth_date notes  \
 0          PESA841            PESA841           28  <NA>        NaT  <NA>
 1          PESA900            PESA900           29  <NA>        NaT  <NA>
 2         PESA1521           PESA1521           38  <NA>        NaT  <NA>
 3         PESA3481           PESA3481           58  <NA>        NaT  <NA>
 4         PESA3600           PESA3600           59  <NA>        NaT  <NA>
 ...            ...                ...          ...   ...        ...   ...
 996   PESA17875984       PESA17875984         4227  <NA>        NaT  <NA>
 997   PESA17918289       PESA17918289         4232  <NA>        NaT  <NA>
 998   PESA17926756       PESA17926756         4233  <NA>        NaT  <NA>
 999   PESA17952169       PESA17952169         4236  <NA>        NaT  <NA>
 1000  PESA18028516       PESA18028516         4245  <NA>        NaT  <NA>

        source_batch_id                 updated_at
 0     derived_subjects  2026-04-10T15:09:37+00:00
 1     derived_subjects  2026-04-10T15:09:37+00:00
 2     derived_subjects  2026-04-10T15:09:37+00:00
 3     derived_subjects  2026-04-10T15:09:37+00:00
 4     derived_subjects  2026-04-10T15:09:37+00:00
 ...                ...                        ...
 996   derived_subjects  2026-04-10T15:09:43+00:00
 997   derived_subjects  2026-04-10T15:09:43+00:00
 998   derived_subjects  2026-04-10T15:09:43+00:00
 999   derived_subjects  2026-04-10T15:09:43+00:00
 1000  derived_subjects  2026-04-10T15:09:43+00:00

 [1001 rows x 8 columns]}

In [ ]:
# print(repo.catalog.list_tables())
# print(repo.catalog.variable_entries())
# print(repo.get("source_tables").sort_values(["source_file", "source_sheet", "source_kind"]))

['assets', 'clinical_measurements', 'cohort_membership', 'image_measurements', 'scans', 'sessions', 'source_tables', 'subject_ids', 'subjects']
[]
Empty DataFrame
Columns: [source_uid, source_file, source_sheet, source_kind, domain, modality, layout, n_rows, n_columns, columns_json, source_batch_id, updated_at]
Index: []

In [5]:
subject_ids = repo.get("subject_ids", wide=True)
subject_ids

,subject_uid,id_namespace,id_value,id_source,is_primary,source_batch_id,updated_at
0,PESA841,mri_id,BMRI290077,PESABrain_All_IDs::Sheet1,False,trial_ids_001,2026-04-10T15:09:37+00:00
1,PESA841,medrecon_id,RE629534,PESABrain_All_IDs::Sheet1,False,trial_ids_001,2026-04-10T15:09:37+00:00
2,PESA841,psicosocial_id,PS366003,PESABrain_All_IDs::Sheet1,False,trial_ids_001,2026-04-10T15:09:37+00:00
3,PESA900,mri_id,BMRI590175,PESABrain_All_IDs::Sheet1,False,trial_ids_001,2026-04-10T15:09:37+00:00
4,PESA900,medrecon_id,RE536721,PESABrain_All_IDs::Sheet1,False,trial_ids_001,2026-04-10T15:09:37+00:00
...,...,...,...,...,...,...,...
8256,PESA9897316,patient_id,PESA9897316,PESABrain_4DFlow_LocalizedTimeseriesFlow_Wide_...,True,trial_ids_001,2026-04-10T16:00:18+00:00
8257,PESA9928801,patient_id,PESA9928801,PESABrain_4DFlow_LocalizedTimeseriesFlow_Wide_...,True,trial_ids_001,2026-04-10T16:00:18+00:00
8258,PESA9935104,patient_id,PESA9935104,PESABrain_4DFlow_LocalizedTimeseriesFlow_Wide_...,True,trial_ids_001,2026-04-10T16:00:18+00:00
8259,PESA9947716,patient_id,PESA9947716,PESABrain_4DFlow_LocalizedTimeseriesFlow_Wide_...,True,trial_ids_001,2026-04-10T16:00:18+00:00
8260,PESA9972964,patient_id,PESA9972964,PESABrain_4DFlow_LocalizedTimeseriesFlow_Wide_...,True,trial_ids_001,2026-04-10T16:00:18+00:00

In [ ]:
# Remove

# empty = repo.get("subject_ids").iloc[0:0]
# repo.write_table("subject_ids", empty, provenance={"importer": "undo batch {trial_id}"})

# empty = repo.get("clinical_measurements").iloc[0:0]
# repo.write_table("clinical_measurements", empty, provenance={"importer": "undo batch {trial_id}"})

# empty = repo.get("image_measurements").iloc[0:0]
# repo.write_table("image_measurements", empty, provenance={"importer": "undo batch {trial_id}"})

# src = repo.get("source_tables")
# src = src[src["source_batch_id"] != trial_id]
# repo.write_table(
#   "source_tables",
#   src,
#   provenance={"reason": f"undo batch {trial_id}"},
# )

PosixPath('/home/imarcoss/nvitk/notebooks/prototypes/dataset/tables/image_measurements.parquet')

In [9]:
res = import_pesabrain_source(
    repo,
    db_base,
    "PESABrain_All_4DFlow_IDs.xlsx",
    sheet="Sheet1",
    source_kind="subject_ids",
    source_batch_id=trial_id,
)

res

{'filename': 'PESABrain_All_4DFlow_IDs.xlsx',
 'sheet': 'Sheet1',
 'source_kind': 'subject_ids',
 'result':        subject_uid    id_namespace      id_value  \
 0         PESA1521      patient_id      PESA1521
 1         PESA1521          mri_id    BMRI418006
 2         PESA1521            seqn            38
 3         PESA1521     medrecon_id      RE435268
 4         PESA1521  psicosocial_id      PS387117
 ...            ...             ...           ...
 2972  PESA17918289      patient_id  PESA17918289
 2973  PESA17918289          mri_id    BMRI678512
 2974  PESA17918289            seqn          4232
 2975  PESA17918289     medrecon_id      RE501918
 2976  PESA17918289  psicosocial_id      PS847159

                              id_source  is_primary source_batch_id  \
 0     PESABrain_All_4DFlow_IDs::Sheet1        True   trial_ids_001
 1     PESABrain_All_4DFlow_IDs::Sheet1       False   trial_ids_001
 2     PESABrain_All_4DFlow_IDs::Sheet1        True   trial_ids_001
 3     PESABrain_All_4DFlow_IDs::Sheet1       False   trial_ids_001
 4     PESABrain_All_4DFlow_IDs::Sheet1       False   trial_ids_001
 ...                                ...         ...             ...
 2972  PESABrain_All_4DFlow_IDs::Sheet1        True   trial_ids_001
 2973  PESABrain_All_4DFlow_IDs::Sheet1       False   trial_ids_001
 2974  PESABrain_All_4DFlow_IDs::Sheet1        True   trial_ids_001
 2975  PESABrain_All_4DFlow_IDs::Sheet1       False   trial_ids_001
 2976  PESABrain_All_4DFlow_IDs::Sheet1       False   trial_ids_001

                      updated_at
 0     2026-04-10T15:12:56+00:00
 1     2026-04-10T15:12:56+00:00
 2     2026-04-10T15:12:56+00:00
 3     2026-04-10T15:12:56+00:00
 4     2026-04-10T15:12:56+00:00
 ...                         ...
 2972  2026-04-10T15:12:56+00:00
 2973  2026-04-10T15:12:56+00:00
 2974  2026-04-10T15:12:56+00:00
 2975  2026-04-10T15:12:56+00:00
 2976  2026-04-10T15:12:56+00:00

 [2977 rows x 7 columns],
 'subjects':        subject_uid primary_patient_id primary_seqn   sex birth_date notes  \
 0          PESA841            PESA841           28  <NA>        NaT  <NA>
 1          PESA900            PESA900           29  <NA>        NaT  <NA>
 2         PESA3481           PESA3481           58  <NA>        NaT  <NA>
 3         PESA3600           PESA3600           59  <NA>        NaT  <NA>
 4         PESA4225           PESA4225           64  <NA>        NaT  <NA>
 ...            ...                ...          ...   ...        ...   ...
 996   PESA17808400       PESA17808400         4219  <NA>        NaT  <NA>
 997   PESA17859076       PESA17859076         4225  <NA>        NaT  <NA>
 998   PESA17867529       PESA17867529         4226  <NA>        NaT  <NA>
 999   PESA17875984       PESA17875984         4227  <NA>        NaT  <NA>
 1000  PESA17918289       PESA17918289         4232  <NA>        NaT  <NA>

        source_batch_id                 updated_at
 0     derived_subjects  2026-04-10T15:12:57+00:00
 1     derived_subjects  2026-04-10T15:12:57+00:00
 2     derived_subjects  2026-04-10T15:12:57+00:00
 3     derived_subjects  2026-04-10T15:12:57+00:00
 4     derived_subjects  2026-04-10T15:12:57+00:00
 ...                ...                        ...
 996   derived_subjects  2026-04-10T15:13:02+00:00
 997   derived_subjects  2026-04-10T15:13:02+00:00
 998   derived_subjects  2026-04-10T15:13:02+00:00
 999   derived_subjects  2026-04-10T15:13:02+00:00
 1000  derived_subjects  2026-04-10T15:13:02+00:00

 [1001 rows x 8 columns]}

In [12]:
import_pesabrain_source(
    repo,
    db_base,
    "PESABrain_SubjectCatalog_AllXNAT_20260216.xlsx",
    sheet="Datos",
    source_kind="subject_catalog",
    source_batch_id=trial_id,
)

{'filename': 'PESABrain_SubjectCatalog_AllXNAT_20260216.xlsx',
 'sheet': 'Datos',
 'source_kind': 'subject_catalog',
 'result':     session_uid   subject_uid project_id experiment_label modality  \
 0    BMRI100102  PESA14100025   local_db       BMRI100102       mr
 1    BMRI101198   PESA5184729   local_db       BMRI101198       mr
 2    BMRI101846     PESA87616   local_db       BMRI101846       mr
 3    BMRI103891   PESA7001316   local_db       BMRI103891       mr
 4    BMRI104117  PESA10233601   local_db       BMRI104117       mr
 ..          ...           ...        ...              ...      ...
 973  BMRI996396    PESA760384   local_db       BMRI996396       mr
 974  BMRI997033   PESA1901641   local_db       BMRI997033       mr
 975  BMRI997363   PESA1420864   local_db       BMRI997363       mr
 976  BMRI999786   PESA6482116   local_db       BMRI999786       mr
 977  BMRI999915  PESA14017536   local_db       BMRI999915       mr

     visit_label   scanner                                    available_scans  \
 0          <NA>  DIONISIO  3D T1(1), 3D_FLAIR(1), 3D_T2 HR(1), COR(1), DT...
 1          <NA>  DIONISIO  3D T1(1), 3D_FLAIR(1), 3D_T2 HR(1), CO 3D T1(1...
 2          <NA>  DIONISIO  3D T1(1), 3D_FLAIR(1), 3D_T2 HR(1), DTI NODDI(...
 3          <NA>  DIONISIO  3D T1(1), 3D_FLAIR(1), 3D_T2 HR(1), AP 4DQflow...
 4          <NA>  DIONISIO  3D T1(1), 3D_FLAIR(1), 3D_T2 HR(1), 4DQflowNeu...
 ..          ...       ...                                                ...
 973        <NA>  DIONISIO  3D T1(1), 3D_FLAIR(1), 3D_T2 HR(1), DTI NODDI(...
 974        <NA>  DIONISIO  3D T1(1), 3D_FLAIR(1), 3D_T2 HR(1), COR(1), DT...
 975        <NA>  DIONISIO  3D T1(1), 3D_FLAIR(1), 3D_T2 HR(1), DTI NODDI(...
 976        <NA>  DIONISIO  3D T1(1), 3D_FLAIR(1), 3D_T2 HR(1), 4DQflowNeu...
 977        <NA>  DIONISIO  3D T1(1), 3D_FLAIR(1), 3D_T2 HR(1), AP 4DQflow...

     acquired_at                                     source_file source_sheet  \
 0    2024-10-15  PESABrain_SubjectCatalog_AllXNAT_20260216.xlsx        Datos
 1    2022-09-30  PESABrain_SubjectCatalog_AllXNAT_20260216.xlsx        Datos
 2    2022-02-15  PESABrain_SubjectCatalog_AllXNAT_20260216.xlsx        Datos
 3    2024-11-12  PESABrain_SubjectCatalog_AllXNAT_20260216.xlsx        Datos
 4    2023-02-24  PESABrain_SubjectCatalog_AllXNAT_20260216.xlsx        Datos
 ..          ...                                             ...          ...
 973  2021-06-23  PESABrain_SubjectCatalog_AllXNAT_20260216.xlsx        Datos
 974  2024-09-17  PESABrain_SubjectCatalog_AllXNAT_20260216.xlsx        Datos
 975  2022-03-18  PESABrain_SubjectCatalog_AllXNAT_20260216.xlsx        Datos
 976  2023-06-23  PESABrain_SubjectCatalog_AllXNAT_20260216.xlsx        Datos
 977  2025-01-31  PESABrain_SubjectCatalog_AllXNAT_20260216.xlsx        Datos

     source_batch_id                 updated_at
 0     trial_ids_001  2026-04-10T15:16:21+00:00
 1     trial_ids_001  2026-04-10T15:16:21+00:00
 2     trial_ids_001  2026-04-10T15:16:21+00:00
 3     trial_ids_001  2026-04-10T15:16:21+00:00
 4     trial_ids_001  2026-04-10T15:16:21+00:00
 ..              ...                        ...
 973   trial_ids_001  2026-04-10T15:16:21+00:00
 974   trial_ids_001  2026-04-10T15:16:21+00:00
 975   trial_ids_001  2026-04-10T15:16:21+00:00
 976   trial_ids_001  2026-04-10T15:16:21+00:00
 977   trial_ids_001  2026-04-10T15:16:21+00:00

 [978 rows x 13 columns],
 'subjects':        subject_uid primary_patient_id primary_seqn   sex birth_date notes  \
 0          PESA841            PESA841           28  <NA>        NaT  <NA>
 1          PESA900            PESA900           29  <NA>        NaT  <NA>
 2         PESA3481           PESA3481           58  <NA>        NaT  <NA>
 3         PESA3600           PESA3600           59  <NA>        NaT  <NA>
 4         PESA4225           PESA4225           64  <NA>        NaT  <NA>
 ...            ...                ...          ...   ...        ...   ...
 996   PESA17808400       PESA17808400         4219  <NA>        NaT  <NA>
 997   PESA17859076       PESA17859076         4225  <NA>        NaT  <NA>
 998   PESA17867529       PESA17867529         4226  <NA>        NaT  <NA>
 999   PESA17875984       PESA17875984         4227  <NA>        NaT  <NA>
 1000  PESA17918289       PESA17918289         4232  <NA>        NaT  <NA>

        source_batch_id                 updated_at
 0     derived_subjects  2026-04-10T15:16:21+00:00
 1     derived_subjects  2026-04-10T15:16:21+00:00
 2     derived_subjects  2026-04-10T15:16:21+00:00
 3     derived_subjects  2026-04-10T15:16:21+00:00
 4     derived_subjects  2026-04-10T15:16:21+00:00
 ...                ...                        ...
 996   derived_subjects  2026-04-10T15:16:27+00:00
 997   derived_subjects  2026-04-10T15:16:27+00:00
 998   derived_subjects  2026-04-10T15:16:27+00:00
 999   derived_subjects  2026-04-10T15:16:27+00:00
 1000  derived_subjects  2026-04-10T15:16:27+00:00

 [1001 rows x 8 columns]}

In [5]:
import_pesabrain_source(
    repo,
    db_base,
    "PESABrain_Clinical_20260216.xlsx",
    sheet="Sheet1",
    source_kind="clinical_wide",
    source_batch_id=trial_id,
)

{'filename': 'PESABrain_Clinical_20260216.xlsx',
 'sheet': 'Sheet1',
 'source_kind': 'clinical_wide',
 'result':         subject_uid visit_id variable_id  value_num value_text  unit  \
 0           PESA841        4        seqn  28.000000       <NA>  <NA>
 1           PESA900        4        seqn  29.000000       <NA>  <NA>
 2          PESA1521        4        seqn  38.000000       <NA>  <NA>
 3          PESA3481        4        seqn  58.000000       <NA>  <NA>
 4          PESA3600        4        seqn  59.000000       <NA>  <NA>
 ...             ...      ...         ...        ...        ...   ...
 20983  PESA17867529        4  pedframi30   0.103115       <NA>  <NA>
 20984  PESA17875984        4  pedframi30   0.103026       <NA>  <NA>
 20985  PESA17918289        4  pedframi30   0.168181       <NA>  <NA>
 20986  PESA17952169        4  pedframi30   0.166641       <NA>  <NA>
 20987  PESA18028516        4  pedframi30   0.097296       <NA>  <NA>

       value_kind                         source_table  \
 0        numeric  PESABrain_Clinical_20260216::Sheet1
 1        numeric  PESABrain_Clinical_20260216::Sheet1
 2        numeric  PESABrain_Clinical_20260216::Sheet1
 3        numeric  PESABrain_Clinical_20260216::Sheet1
 4        numeric  PESABrain_Clinical_20260216::Sheet1
 ...          ...                                  ...
 20983    numeric  PESABrain_Clinical_20260216::Sheet1
 20984    numeric  PESABrain_Clinical_20260216::Sheet1
 20985    numeric  PESABrain_Clinical_20260216::Sheet1
 20986    numeric  PESABrain_Clinical_20260216::Sheet1
 20987    numeric  PESABrain_Clinical_20260216::Sheet1

                             source_file source_sheet source_column  \
 0      PESABrain_Clinical_20260216.xlsx       Sheet1          seqn
 1      PESABrain_Clinical_20260216.xlsx       Sheet1          seqn
 2      PESABrain_Clinical_20260216.xlsx       Sheet1          seqn
 3      PESABrain_Clinical_20260216.xlsx       Sheet1          seqn
 4      PESABrain_Clinical_20260216.xlsx       Sheet1          seqn
 ...                                 ...          ...           ...
 20983  PESABrain_Clinical_20260216.xlsx       Sheet1    PEDFRAMI30
 20984  PESABrain_Clinical_20260216.xlsx       Sheet1    PEDFRAMI30
 20985  PESABrain_Clinical_20260216.xlsx       Sheet1    PEDFRAMI30
 20986  PESABrain_Clinical_20260216.xlsx       Sheet1    PEDFRAMI30
 20987  PESABrain_Clinical_20260216.xlsx       Sheet1    PEDFRAMI30

       source_batch_id measured_at
 0       trial_ids_001         NaT
 1       trial_ids_001         NaT
 2       trial_ids_001         NaT
 3       trial_ids_001         NaT
 4       trial_ids_001         NaT
 ...               ...         ...
 20983   trial_ids_001         NaT
 20984   trial_ids_001         NaT
 20985   trial_ids_001         NaT
 20986   trial_ids_001         NaT
 20987   trial_ids_001         NaT

 [20988 rows x 13 columns],
 'subjects':        subject_uid primary_patient_id primary_seqn     sex birth_date notes  \
 0          PESA841            PESA841           28    Male        NaT  <NA>
 1          PESA900            PESA900           29  Female        NaT  <NA>
 2         PESA3481           PESA3481           58    Male        NaT  <NA>
 3         PESA3600           PESA3600           59    Male        NaT  <NA>
 4         PESA4225           PESA4225           64  Female        NaT  <NA>
 ...            ...                ...          ...     ...        ...   ...
 996   PESA17808400       PESA17808400         4219  Female        NaT  <NA>
 997   PESA17859076       PESA17859076         4225    Male        NaT  <NA>
 998   PESA17867529       PESA17867529         4226    Male        NaT  <NA>
 999   PESA17875984       PESA17875984         4227  Female        NaT  <NA>
 1000  PESA17918289       PESA17918289         4232    Male        NaT  <NA>

        source_batch_id                 updated_at
 0     derived_subjects  2026-04-10T15:52:49+00:00
 1     derived_subjects  2026-04-10T15:52:49+00:00
 2     derived_subjects  2026-04-10T15:52:49+00:00
 3     derived_subjects  2026-04-10T15:52:49+00:00
 4     derived_subjects  2026-04-10T15:52:49+00:00
 ...                ...                        ...
 996   derived_subjects  2026-04-10T15:53:01+00:00
 997   derived_subjects  2026-04-10T15:53:01+00:00
 998   derived_subjects  2026-04-10T15:53:01+00:00
 999   derived_subjects  2026-04-10T15:53:01+00:00
 1000  derived_subjects  2026-04-10T15:53:01+00:00

 [1001 rows x 8 columns]}

In [6]:
import_pesabrain_source(repo, db_base, "PESABrain_APOE_20260318.xlsx", sheet="Sheet1", source_kind="clinical_wide", source_batch_id=trial_id)
import_pesabrain_source(repo, db_base, "PESABrain_TAC_20260318.xlsx", sheet="Sheet1", source_kind="clinical_wide", source_batch_id=trial_id)
import_pesabrain_source(repo, db_base, "PESABrain_Echography_CarotidePlaque_20260216.xlsx", sheet="Sheet1", source_kind="clinical_wide", source_batch_id=trial_id)

{'filename': 'PESABrain_Echography_CarotidePlaque_20260216.xlsx',
 'sheet': 'Sheet1',
 'source_kind': 'clinical_wide',
 'result':        subject_uid visit_id               variable_id  value_num value_text  \
 0          PESA841        4                patient_id        NaN    PESA841
 1          PESA900        4                patient_id        NaN    PESA900
 2         PESA1521        4                patient_id        NaN   PESA1521
 3         PESA3481        4                patient_id        NaN   PESA3481
 4         PESA3600        4                patient_id        NaN   PESA3600
 ...            ...      ...                       ...        ...        ...
 5993  PESA17859076        4  total_carotid_plaque_vol   0.000000       <NA>
 5994  PESA17867529        4  total_carotid_plaque_vol  48.220704       <NA>
 5995  PESA17875984        4  total_carotid_plaque_vol   0.000000       <NA>
 5996  PESA17918289        4  total_carotid_plaque_vol  10.727136       <NA>
 5997  PESA17952169        4  total_carotid_plaque_vol   0.000000       <NA>

       unit value_kind                                       source_table  \
 0     <NA>       text  PESABrain_Echography_CarotidePlaque_20260216::...
 1     <NA>       text  PESABrain_Echography_CarotidePlaque_20260216::...
 2     <NA>       text  PESABrain_Echography_CarotidePlaque_20260216::...
 3     <NA>       text  PESABrain_Echography_CarotidePlaque_20260216::...
 4     <NA>       text  PESABrain_Echography_CarotidePlaque_20260216::...
 ...    ...        ...                                                ...
 5993  <NA>    numeric  PESABrain_Echography_CarotidePlaque_20260216::...
 5994  <NA>    numeric  PESABrain_Echography_CarotidePlaque_20260216::...
 5995  <NA>    numeric  PESABrain_Echography_CarotidePlaque_20260216::...
 5996  <NA>    numeric  PESABrain_Echography_CarotidePlaque_20260216::...
 5997  <NA>    numeric  PESABrain_Echography_CarotidePlaque_20260216::...

                                             source_file source_sheet  \
 0     PESABrain_Echography_CarotidePlaque_20260216.xlsx       Sheet1
 1     PESABrain_Echography_CarotidePlaque_20260216.xlsx       Sheet1
 2     PESABrain_Echography_CarotidePlaque_20260216.xlsx       Sheet1
 3     PESABrain_Echography_CarotidePlaque_20260216.xlsx       Sheet1
 4     PESABrain_Echography_CarotidePlaque_20260216.xlsx       Sheet1
 ...                                                 ...          ...
 5993  PESABrain_Echography_CarotidePlaque_20260216.xlsx       Sheet1
 5994  PESABrain_Echography_CarotidePlaque_20260216.xlsx       Sheet1
 5995  PESABrain_Echography_CarotidePlaque_20260216.xlsx       Sheet1
 5996  PESABrain_Echography_CarotidePlaque_20260216.xlsx       Sheet1
 5997  PESABrain_Echography_CarotidePlaque_20260216.xlsx       Sheet1

                  source_column source_batch_id measured_at
 0                   patient_id   trial_ids_001         NaT
 1                   patient_id   trial_ids_001         NaT
 2                   patient_id   trial_ids_001         NaT
 3                   patient_id   trial_ids_001         NaT
 4                   patient_id   trial_ids_001         NaT
 ...                        ...             ...         ...
 5993  total_carotid_plaque_vol   trial_ids_001         NaT
 5994  total_carotid_plaque_vol   trial_ids_001         NaT
 5995  total_carotid_plaque_vol   trial_ids_001         NaT
 5996  total_carotid_plaque_vol   trial_ids_001         NaT
 5997  total_carotid_plaque_vol   trial_ids_001         NaT

 [5998 rows x 13 columns],
 'subjects':        subject_uid primary_patient_id primary_seqn     sex birth_date notes  \
 0          PESA841            PESA841           28    Male        NaT  <NA>
 1          PESA900            PESA900           29  Female        NaT  <NA>
 2         PESA3481           PESA3481           58    Male        NaT  <NA>
 3         PESA3600           PESA3600           59    Male        NaT  <NA>
 4         PESA4225           PESA4225           64  Female        NaT  <NA>
 ...            ...                ...          ...     ...        ...   ...
 996   PESA17808400       PESA17808400         4219  Female        NaT  <NA>
 997   PESA17859076       PESA17859076         4225    Male        NaT  <NA>
 998   PESA17867529       PESA17867529         4226    Male        NaT  <NA>
 999   PESA17875984       PESA17875984         4227  Female        NaT  <NA>
 1000  PESA17918289       PESA17918289         4232    Male        NaT  <NA>

        source_batch_id                 updated_at
 0     derived_subjects  2026-04-10T15:53:29+00:00
 1     derived_subjects  2026-04-10T15:53:29+00:00
 2     derived_subjects  2026-04-10T15:53:29+00:00
 3     derived_subjects  2026-04-10T15:53:29+00:00
 4     derived_subjects  2026-04-10T15:53:29+00:00
 ...                ...                        ...
 996   derived_subjects  2026-04-10T15:53:43+00:00
 997   derived_subjects  2026-04-10T15:53:43+00:00
 998   derived_subjects  2026-04-10T15:53:43+00:00
 999   derived_subjects  2026-04-10T15:53:43+00:00
 1000  derived_subjects  2026-04-10T15:53:43+00:00

 [1001 rows x 8 columns]}

In [5]:
import_pesabrain_source(repo, db_base, "PESABrain_4DFlow_LocalizedPI_20260216.xlsx", sheet="PESABrain_AnalysisDB_Batch1", source_kind="image_wide", source_batch_id=trial_id)
import_pesabrain_source(repo, db_base, "PESABrain_4DFlow_LocalizedTimeAvgFlow_20260216.xlsx", sheet="PESABrain_AnalysisDB_Batch1", source_kind="image_wide", source_batch_id=trial_id)

{'filename': 'PESABrain_4DFlow_LocalizedTimeAvgFlow_20260216.xlsx',
 'sheet': 'PESABrain_AnalysisDB_Batch1',
 'source_kind': 'image_wide',
 'result':        subject_uid modality            region_id         region_label  \
 0      PESA1006009   4dflow           patient_id           patient_id
 1     PESA10061584   4dflow           patient_id           patient_id
 2     PESA10067929   4dflow           patient_id           patient_id
 3     PESA10086976   4dflow           patient_id           patient_id
 4     PESA10112400   4dflow           patient_id           patient_id
 ...            ...      ...                  ...                  ...
 5243   PESA8910225   4dflow  right_communicating  Right Communicating
 5244   PESA9120400   4dflow  right_communicating  Right Communicating
 5245   PESA9241600   4dflow  right_communicating  Right Communicating
 5246   PESA9511056   4dflow  right_communicating  Right Communicating
 5247   PESA9928801   4dflow  right_communicating  Right Communicating

       frame_index variable_id  value_num    value_text  unit value_kind  \
 0            <NA>   flow_mean        NaN   PESA1006009  <NA>       text
 1            <NA>   flow_mean        NaN  PESA10061584  <NA>       text
 2            <NA>   flow_mean        NaN  PESA10067929  <NA>       text
 3            <NA>   flow_mean        NaN  PESA10086976  <NA>       text
 4            <NA>   flow_mean        NaN  PESA10112400  <NA>       text
 ...           ...         ...        ...           ...   ...        ...
 5243         <NA>   flow_mean  38.298606          <NA>  <NA>    numeric
 5244         <NA>   flow_mean  60.386735          <NA>  <NA>    numeric
 5245         <NA>   flow_mean  80.977746          <NA>  <NA>    numeric
 5246         <NA>   flow_mean  22.014788          <NA>  <NA>    numeric
 5247         <NA>   flow_mean  82.117245          <NA>  <NA>    numeric

                                        pipeline_name pipeline_version  \
 0     PESABrain_4DFlow_LocalizedTimeAvgFlow_20260216             <NA>
 1     PESABrain_4DFlow_LocalizedTimeAvgFlow_20260216             <NA>
 2     PESABrain_4DFlow_LocalizedTimeAvgFlow_20260216             <NA>
 3     PESABrain_4DFlow_LocalizedTimeAvgFlow_20260216             <NA>
 4     PESABrain_4DFlow_LocalizedTimeAvgFlow_20260216             <NA>
 ...                                              ...              ...
 5243  PESABrain_4DFlow_LocalizedTimeAvgFlow_20260216             <NA>
 5244  PESABrain_4DFlow_LocalizedTimeAvgFlow_20260216             <NA>
 5245  PESABrain_4DFlow_LocalizedTimeAvgFlow_20260216             <NA>
 5246  PESABrain_4DFlow_LocalizedTimeAvgFlow_20260216             <NA>
 5247  PESABrain_4DFlow_LocalizedTimeAvgFlow_20260216             <NA>

      qc_status source_asset  \
 0         <NA>         <NA>
 1         <NA>         <NA>
 2         <NA>         <NA>
 3         <NA>         <NA>
 4         <NA>         <NA>
 ...        ...          ...
 5243      <NA>         <NA>
 5244      <NA>         <NA>
 5245      <NA>         <NA>
 5246      <NA>         <NA>
 5247      <NA>         <NA>

                                            source_table  \
 0     PESABrain_4DFlow_LocalizedTimeAvgFlow_20260216...
 1     PESABrain_4DFlow_LocalizedTimeAvgFlow_20260216...
 2     PESABrain_4DFlow_LocalizedTimeAvgFlow_20260216...
 3     PESABrain_4DFlow_LocalizedTimeAvgFlow_20260216...
 4     PESABrain_4DFlow_LocalizedTimeAvgFlow_20260216...
 ...                                                 ...
 5243  PESABrain_4DFlow_LocalizedTimeAvgFlow_20260216...
 5244  PESABrain_4DFlow_LocalizedTimeAvgFlow_20260216...
 5245  PESABrain_4DFlow_LocalizedTimeAvgFlow_20260216...
 5246  PESABrain_4DFlow_LocalizedTimeAvgFlow_20260216...
 5247  PESABrain_4DFlow_LocalizedTimeAvgFlow_20260216...

                                             source_file  \
 0     PESABrain_4DFlow_LocalizedTimeAvgFlow_20260216...
 1     PESABrain_4DFlow_LocalizedTimeAvgFlow_20260216...
 2     PESABrain_4DFlow_LocalizedTimeAvgFlow_20260216...
 3     PESABrain_4DFlow_LocalizedTimeAvgFlow_20260216...
 4     PESABrain_4DFlow_LocalizedTimeAvgFlow_20260216...
 ...                                                 ...
 5243  PESABrain_4DFlow_LocalizedTimeAvgFlow_20260216...
 5244  PESABrain_4DFlow_LocalizedTimeAvgFlow_20260216...
 5245  PESABrain_4DFlow_LocalizedTimeAvgFlow_20260216...
 5246  PESABrain_4DFlow_LocalizedTimeAvgFlow_20260216...
 5247  PESABrain_4DFlow_LocalizedTimeAvgFlow_20260216...

                      source_sheet        source_column source_batch_id  \
 0     PESABrain_AnalysisDB_Batch1           patient_id   trial_ids_001
 1     PESABrain_AnalysisDB_Batch1           patient_id   trial_ids_001
 2     PESABrain_AnalysisDB_Batch1           patient_id   trial_ids_001
 3     PESABrain_AnalysisDB_Batch1           patient_id   trial_ids_001
 4     PESABrain_AnalysisDB_Batch1           patient_id   trial_ids_001
 ...                           ...                  ...             ...
 5243  PESABrain_AnalysisDB_Batch1  Right Communicating   trial_ids_001
 5244  PESABrain_AnalysisDB_Batch1  Right Communicating   trial_ids_001
 5245  PESABrain_AnalysisDB_Batch1  Right Communicating   trial_ids_001
 5246  PESABrain_AnalysisDB_Batch1  Right Communicating   trial_ids_001
 5247  PESABrain_AnalysisDB_Batch1  Right Communicating   trial_ids_001

      measured_at
 0            NaT
 1            NaT
 2            NaT
 3            NaT
 4            NaT
 ...          ...
 5243         NaT
 5244         NaT
 5245         NaT
 5246         NaT
 5247         NaT

 [5248 rows x 20 columns],
 'subjects':        subject_uid primary_patient_id primary_seqn     sex birth_date notes  \
 0          PESA841            PESA841           28    Male        NaT  <NA>
 1          PESA900            PESA900           29  Female        NaT  <NA>
 2         PESA3481           PESA3481           58    Male        NaT  <NA>
 3         PESA3600           PESA3600           59    Male        NaT  <NA>
 4         PESA4225           PESA4225           64  Female        NaT  <NA>
 ...            ...                ...          ...     ...        ...   ...
 996   PESA17918289       PESA17918289         4232    Male        NaT  <NA>
 997    PESA3003289        PESA3003289         1732  Female        NaT  <NA>
 998   PESA13046544       PESA13046544         3611  Female        NaT  <NA>
 999   PESA10989225       PESA10989225         3314    Male        NaT  <NA>
 1000   PESA5313025        PESA5313025         2304  Female        NaT  <NA>

        source_batch_id                 updated_at
 0     derived_subjects  2026-04-10T16:53:09+00:00
 1     derived_subjects  2026-04-10T16:53:09+00:00
 2     derived_subjects  2026-04-10T16:53:09+00:00
 3     derived_subjects  2026-04-10T16:53:09+00:00
 4     derived_subjects  2026-04-10T16:53:09+00:00
 ...                ...                        ...
 996   derived_subjects  2026-04-10T16:53:22+00:00
 997   derived_subjects  2026-04-10T16:53:22+00:00
 998   derived_subjects  2026-04-10T16:53:22+00:00
 999   derived_subjects  2026-04-10T16:53:22+00:00
 1000  derived_subjects  2026-04-10T16:53:22+00:00

 [1001 rows x 8 columns]}

In [6]:
# import_pesabrain_source(repo, db_base, "PESABrain_4DFlow_LocalizedTimeseriesFlow_20260216.xlsx", sheet="Datos", source_kind="image_timeseries_long", source_batch_id=trial_id)
import_pesabrain_source(repo, db_base, "PESABrain_4DFlow_LocalizedTimeseriesFlow_Wide_20260216.xlsx", sheet="Datos", source_kind="image_timeseries_wide", source_batch_id=trial_id)

{'filename': 'PESABrain_4DFlow_LocalizedTimeseriesFlow_Wide_20260216.xlsx',
 'sheet': 'Datos',
 'source_kind': 'image_timeseries_wide',
 'result':        subject_uid modality region_id      region_label  frame_index  \
 0      PESA1006009   4dflow      basi           Basilar            0
 1      PESA1006009   4dflow      laca          Left ACA            0
 2      PESA1006009   4dflow      lica          Left ICA            0
 3      PESA1006009   4dflow      lmca          Left MCA            0
 4      PESA1006009   4dflow      lpca          Left PCA            0
 ...            ...      ...       ...               ...          ...
 71950  PESA9972964   4dflow      rpca         Right PCA           14
 71951  PESA9972964   4dflow      rtsv  Right Transverse           14
 71952  PESA9972964   4dflow      sssv     Sagital Sinus           14
 71953  PESA9972964   4dflow      strv    Straight Sinus           14
 71954  PESA9972964   4dflow      tcbf              TCBF           14

         variable_id   value_num value_text  unit value_kind  \
 0      flow_tseries  171.740742       <NA>  <NA>    numeric
 1      flow_tseries  130.583167       <NA>  <NA>    numeric
 2      flow_tseries  252.617741       <NA>  <NA>    numeric
 3      flow_tseries  182.312708       <NA>  <NA>    numeric
 4      flow_tseries   79.050901       <NA>  <NA>    numeric
 ...             ...         ...        ...   ...        ...
 71950  flow_tseries  132.937260       <NA>  <NA>    numeric
 71951  flow_tseries   99.025147       <NA>  <NA>    numeric
 71952  flow_tseries  374.781504       <NA>  <NA>    numeric
 71953  flow_tseries   71.346781       <NA>  <NA>    numeric
 71954  flow_tseries  852.391434       <NA>  <NA>    numeric

                                            pipeline_name pipeline_version  \
 0      PESABrain_4DFlow_LocalizedTimeseriesFlow_Wide_...             <NA>
 1      PESABrain_4DFlow_LocalizedTimeseriesFlow_Wide_...             <NA>
 2      PESABrain_4DFlow_LocalizedTimeseriesFlow_Wide_...             <NA>
 3      PESABrain_4DFlow_LocalizedTimeseriesFlow_Wide_...             <NA>
 4      PESABrain_4DFlow_LocalizedTimeseriesFlow_Wide_...             <NA>
 ...                                                  ...              ...
 71950  PESABrain_4DFlow_LocalizedTimeseriesFlow_Wide_...             <NA>
 71951  PESABrain_4DFlow_LocalizedTimeseriesFlow_Wide_...             <NA>
 71952  PESABrain_4DFlow_LocalizedTimeseriesFlow_Wide_...             <NA>
 71953  PESABrain_4DFlow_LocalizedTimeseriesFlow_Wide_...             <NA>
 71954  PESABrain_4DFlow_LocalizedTimeseriesFlow_Wide_...             <NA>

       qc_status source_asset  \
 0          <NA>         <NA>
 1          <NA>         <NA>
 2          <NA>         <NA>
 3          <NA>         <NA>
 4          <NA>         <NA>
 ...         ...          ...
 71950      <NA>         <NA>
 71951      <NA>         <NA>
 71952      <NA>         <NA>
 71953      <NA>         <NA>
 71954      <NA>         <NA>

                                             source_table  \
 0      PESABrain_4DFlow_LocalizedTimeseriesFlow_Wide_...
 1      PESABrain_4DFlow_LocalizedTimeseriesFlow_Wide_...
 2      PESABrain_4DFlow_LocalizedTimeseriesFlow_Wide_...
 3      PESABrain_4DFlow_LocalizedTimeseriesFlow_Wide_...
 4      PESABrain_4DFlow_LocalizedTimeseriesFlow_Wide_...
 ...                                                  ...
 71950  PESABrain_4DFlow_LocalizedTimeseriesFlow_Wide_...
 71951  PESABrain_4DFlow_LocalizedTimeseriesFlow_Wide_...
 71952  PESABrain_4DFlow_LocalizedTimeseriesFlow_Wide_...
 71953  PESABrain_4DFlow_LocalizedTimeseriesFlow_Wide_...
 71954  PESABrain_4DFlow_LocalizedTimeseriesFlow_Wide_...

                                              source_file source_sheet  \
 0      PESABrain_4DFlow_LocalizedTimeseriesFlow_Wide_...        Datos
 1      PESABrain_4DFlow_LocalizedTimeseriesFlow_Wide_...        Datos
 2      PESABrain_4DFlow_LocalizedTimeseriesFlow_Wide_...        Datos
 3      PESABrain_4DFlow_LocalizedTimeseriesFlow_Wide_...        Datos
 4      PESABrain_4DFlow_LocalizedTimeseriesFlow_Wide_...        Datos
 ...                                                  ...          ...
 71950  PESABrain_4DFlow_LocalizedTimeseriesFlow_Wide_...        Datos
 71951  PESABrain_4DFlow_LocalizedTimeseriesFlow_Wide_...        Datos
 71952  PESABrain_4DFlow_LocalizedTimeseriesFlow_Wide_...        Datos
 71953  PESABrain_4DFlow_LocalizedTimeseriesFlow_Wide_...        Datos
 71954  PESABrain_4DFlow_LocalizedTimeseriesFlow_Wide_...        Datos

       source_column source_batch_id measured_at
 0        wide_frame   trial_ids_001         NaT
 1        wide_frame   trial_ids_001         NaT
 2        wide_frame   trial_ids_001         NaT
 3        wide_frame   trial_ids_001         NaT
 4        wide_frame   trial_ids_001         NaT
 ...             ...             ...         ...
 71950    wide_frame   trial_ids_001         NaT
 71951    wide_frame   trial_ids_001         NaT
 71952    wide_frame   trial_ids_001         NaT
 71953    wide_frame   trial_ids_001         NaT
 71954    wide_frame   trial_ids_001         NaT

 [71955 rows x 20 columns],
 'subjects':        subject_uid primary_patient_id primary_seqn     sex birth_date notes  \
 0          PESA841            PESA841           28    Male        NaT  <NA>
 1          PESA900            PESA900           29  Female        NaT  <NA>
 2         PESA3481           PESA3481           58    Male        NaT  <NA>
 3         PESA3600           PESA3600           59    Male        NaT  <NA>
 4         PESA4225           PESA4225           64  Female        NaT  <NA>
 ...            ...                ...          ...     ...        ...   ...
 996   PESA17918289       PESA17918289         4232    Male        NaT  <NA>
 997    PESA3003289        PESA3003289         1732  Female        NaT  <NA>
 998   PESA13046544       PESA13046544         3611  Female        NaT  <NA>
 999   PESA10989225       PESA10989225         3314    Male        NaT  <NA>
 1000   PESA5313025        PESA5313025         2304  Female        NaT  <NA>

        source_batch_id                 updated_at
 0     derived_subjects  2026-04-10T16:53:26+00:00
 1     derived_subjects  2026-04-10T16:53:26+00:00
 2     derived_subjects  2026-04-10T16:53:26+00:00
 3     derived_subjects  2026-04-10T16:53:26+00:00
 4     derived_subjects  2026-04-10T16:53:26+00:00
 ...                ...                        ...
 996   derived_subjects  2026-04-10T16:53:39+00:00
 997   derived_subjects  2026-04-10T16:53:39+00:00
 998   derived_subjects  2026-04-10T16:53:39+00:00
 999   derived_subjects  2026-04-10T16:53:39+00:00
 1000  derived_subjects  2026-04-10T16:53:39+00:00

 [1001 rows x 8 columns]}

In [7]:
subject_ids = repo.get("image_measurements", wide=True)
subject_ids

,subject_uid,session_id,4dflow__basi__0__flow_tseries,4dflow__basi__10__flow_tseries,4dflow__basi__11__flow_tseries,4dflow__basi__12__flow_tseries,4dflow__basi__13__flow_tseries,4dflow__basi__14__flow_tseries,4dflow__basi__1__flow_tseries,4dflow__basi__2__flow_tseries,...,4dflow__tcbf__14__flow_tseries,4dflow__tcbf__1__flow_tseries,4dflow__tcbf__2__flow_tseries,4dflow__tcbf__3__flow_tseries,4dflow__tcbf__4__flow_tseries,4dflow__tcbf__5__flow_tseries,4dflow__tcbf__6__flow_tseries,4dflow__tcbf__7__flow_tseries,4dflow__tcbf__8__flow_tseries,4dflow__tcbf__9__flow_tseries
0,PESA1006009,,171.740742,262.681961,237.725158,188.848443,191.011362,189.22039,168.193645,152.294641,...,727.567034,649.494753,606.463137,562.566876,546.012039,515.232038,509.18498,621.775017,1009.723005,1034.951191
1,PESA10061584,,167.251668,251.961823,186.144733,178.125043,174.001665,166.416178,155.436301,151.897402,...,445.212278,408.801348,396.871412,380.21008,353.171475,340.879176,413.252456,648.847332,690.338688,675.896037
2,PESA10067929,,234.015326,331.168985,309.25106,264.493818,242.809982,229.040794,209.30181,190.483975,...,915.364294,797.223859,755.551829,705.234675,674.628711,656.867108,595.717149,686.037483,1085.846615,1261.265001
3,PESA10086976,,200.100117,237.502127,246.950941,232.032981,216.727839,218.70542,181.868849,175.903559,...,496.300396,435.099708,410.039873,412.769674,572.399129,675.596531,723.533523,678.01516,670.790344,638.767873
4,PESA10112400,,139.311733,205.431976,183.80147,159.936533,156.501975,155.314536,126.335349,122.262626,...,816.282907,696.278729,652.350383,610.821283,583.927009,547.976339,563.925204,789.131742,1133.20394,1131.318898
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
351,PESA9897316,,146.445465,189.702344,170.77127,172.33788,168.57213,159.571881,146.135516,138.917656,...,638.010478,585.055346,561.464324,529.146681,497.189627,673.436236,987.841702,1012.782512,1001.067524,921.754961
352,PESA9928801,,78.387072,118.553166,109.357817,90.60884,91.994212,86.635509,73.397763,71.107993,...,750.168614,630.361168,594.622107,584.678485,552.168796,513.746209,546.94793,812.871974,1085.476434,1150.988889
353,PESA9935104,,229.139428,351.813755,317.140303,256.308432,260.468359,243.036089,203.757019,207.432761,...,814.345551,683.526349,643.329735,609.152927,589.747496,556.826849,554.038281,713.70183,1068.702307,1065.278807
354,PESA9947716,,253.525257,273.990383,287.376165,289.021425,284.843245,276.262808,221.942196,203.814025,...,874.16748,746.988201,679.195848,656.427326,853.980789,1446.179266,1485.307159,1417.99613,1290.4321,1133.210735
355,PESA9972964,,197.611041,245.183058,252.565899,241.381731,212.511535,210.013647,180.883598,169.744234,...,852.391434,737.805262,685.419645,630.608525,605.474253,571.13162,541.889119,526.695199,508.081684,727.739582

In [12]:
hemo = repo.image(
    modality="4dflow",
    variables=["flow_tseries"],
    regions=["left_ica", "right_ica"],
    # filters={"4dflow__right_ica__flow_mean": {"$gt": 5}},
    wide=True,
)
hemo

Empty DataFrame
Columns: [subject_uid, session_id, modality, region_id, region_label, frame_index, variable_id, value_num, value_text, unit, value_kind, pipeline_name, pipeline_version, qc_status, source_asset, source_table, source_file, source_sheet, source_column, source_batch_id, measured_at]
Index: []

[0 rows x 21 columns]

In [10]:
clinical = repo.clinical(
    # variables=["age_at_mri"],
    # filters={"bpxsym": {"$ge": 140}},
    wide=True,
)
clinical

,subject_uid,visit_id,age_at_mri,apoe,bmi,bpxdim,bpxpls,bpxsym,height,hematocrit,...,sex,sys_dias_delta,tacsctot,tacsctot_group,tad,tas,total_carotid_plaque_vol,total_femoral_plaque_vol,total_plaque_vol,weight
0,PESA10017225,4,51.6,E3/E3,30.119402,82.0,78.0,130.0,167.0,47.0,...,Male,48.0,2.58,g1,80.0,134.0,0.0,0.0,0.0,84.0
1,PESA100489,4,57.58,E3/E4,22.662709,77.0,62.0,128.0,177.0,38.0,...,Male,51.0,0.0,g0,78.0,132.0,0.0,0.0,0.0,71.0
2,PESA10048900,4,NaN,E3/E3,NaN,79.0,62.0,150.0,NaN,NaN,...,Male,71.0,17.36,g1,NaN,NaN,12.903408,0.0,12.903408,NaN
3,PESA10055241,4,64.87,E3/E4,27.398176,70.0,67.0,117.0,173.0,42.0,...,Male,47.0,50.78,g1,70.0,127.0,12.363624,71.302896,83.66652,82.0
4,PESA1006009,4,62.87,E3/E3,27.968016,75.0,62.0,124.0,167.0,47.0,...,Male,49.0,0.0,g0,73.0,122.0,0.0,33.320952,33.320952,78.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
996,PESA9928801,4,62.13,E3/E3,27.041644,73.0,75.0,104.0,172.0,45.0,...,Female,31.0,0.0,g0,75.0,122.0,0.0,0.0,0.0,80.0
997,PESA9935104,4,60.59,E3/E3,19.896194,76.0,60.0,122.0,170.0,45.0,...,Female,46.0,0.0,g0,82.0,136.0,0.0,0.0,0.0,57.5
998,PESA9947716,4,59.13,E3/E3,29.757785,71.0,68.0,114.0,170.0,42.0,...,Male,43.0,2.4,g1,80.0,140.0,0.0,0.0,0.0,86.0
999,PESA9954025,4,52.8,E3/E3,23.875659,79.0,66.0,126.0,179.0,46.0,...,Male,47.0,1.48,g1,80.0,135.0,8.970696,89.389944,98.36064,76.5
1000,PESA9972964,4,53.65,E3/E3,19.322185,74.0,55.0,109.0,171.0,41.0,...,Female,35.0,0.0,g0,65.0,112.0,0.0,0.0,0.0,56.5