In [1]:
import os
import sys
from pathlib import Path

ROOT = Path(os.path.abspath('')).resolve().parents[2]
SRC = ROOT / "src"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))


import nvitk as nv
from nvitk import db
import pandas as pd

In [2]:
from nvitk.db.repo import DataRepo
from nvitk.db.xnat import XnatConnectionConfig, sync_xnat_project

PROJECT="PESA_Brain"

In [3]:


repo = DataRepo("~/nvitk/dataset", auto_scaffold=True)
config = XnatConnectionConfig(
    server='https://xnat.cnic.es',
    project=PROJECT,
    netrc_file='~/.netrc',
    verify=False,
)
config

XnatConnectionConfig(server='https://xnat.cnic.es', project='PESA_Brain', user=None, password=None, netrc_file='~/.netrc', verify=False, default_timeout=600)

In [4]:

frames = sync_xnat_project(
    repo,
    config,
    subjects=["PESA10407076", "PESA16016004"],
    requested_sequences="TOF,4DFLOW_AP,4DFLOW_FH,4DFLOW_RL",  # optional
    download_root="/data_local/LabVF/PESA-Brain/DATA/BatchTest/DICOM_XNAT_TEST/",          # optional
    download_dicoms=False,                # True to populate assets + local DICOM paths
    build_sqlite_index=False,
)
frames

[WARNING] Verify is disabled, this will NOT verify the certificate of SSL connections!
[WARNING] Warnings about invalid certificates will be HIDDEN to avoid spam, but this
[WARNING] means that your connection can be potentially unsafe!

{'subjects':     subject_uid primary_patient_id primary_seqn   sex birth_date notes  \
 0  PESA10407076       PESA10407076         <NA>  <NA>        NaT  <NA>
 1  PESA16016004       PESA16016004         <NA>  <NA>        NaT  <NA>

              source_batch_id                 updated_at
 0  xnat_20260413T092010+0000  2026-04-13T09:20:11+00:00
 1  xnat_20260413T092010+0000  2026-04-13T09:20:12+00:00  ,
 'subject_ids':     subject_uid  id_namespace      id_value   id_source  is_primary  \
 0  PESA10407076  xnat_subject  PESA10407076  PESA_Brain        True
 1  PESA16016004  xnat_subject  PESA16016004  PESA_Brain        True

              source_batch_id                 updated_at
 0  xnat_20260413T092010+0000  2026-04-13T09:20:11+00:00
 1  xnat_20260413T092010+0000  2026-04-13T09:20:12+00:00  ,
 'sessions':                           session_uid   subject_uid  project_id  \
 0  PESA_Brain:PESA10407076:BMRI395267  PESA10407076  PESA_Brain
 1  PESA_Brain:PESA16016004:BMRI611724  PESA16016004  PESA_Brain

   experiment_label modality visit_label acquired_at  \
 0       BMRI395267       mr        <NA>  2025-02-04
 1       BMRI611724       mr        <NA>  2023-11-24

              source_batch_id                 updated_at
 0  xnat_20260413T092010+0000  2026-04-13T09:20:11+00:00
 1  xnat_20260413T092010+0000  2026-04-13T09:20:13+00:00  ,
 'scans':                                   scan_uid  \
 0  PESA_Brain:PESA10407076:BMRI395267:1401
 1  PESA_Brain:PESA10407076:BMRI395267:1402
 2  PESA_Brain:PESA10407076:BMRI395267:1803
 3  PESA_Brain:PESA10407076:BMRI395267:1804
 4  PESA_Brain:PESA10407076:BMRI395267:1805
 5  PESA_Brain:PESA16016004:BMRI611724:1501
 6  PESA_Brain:PESA16016004:BMRI611724:1502
 7  PESA_Brain:PESA16016004:BMRI611724:1903
 8  PESA_Brain:PESA16016004:BMRI611724:1904
 9  PESA_Brain:PESA16016004:BMRI611724:1905

                           session_uid   subject_uid scan_id scan_label  \
 0  PESA_Brain:PESA10407076:BMRI395267  PESA10407076    1401       1401
 1  PESA_Brain:PESA10407076:BMRI395267  PESA10407076    1402       1402
 2  PESA_Brain:PESA10407076:BMRI395267  PESA10407076    1803       1803
 3  PESA_Brain:PESA10407076:BMRI395267  PESA10407076    1804       1804
 4  PESA_Brain:PESA10407076:BMRI395267  PESA10407076    1805       1805
 5  PESA_Brain:PESA16016004:BMRI611724  PESA16016004    1501       1501
 6  PESA_Brain:PESA16016004:BMRI611724  PESA16016004    1502       1502
 7  PESA_Brain:PESA16016004:BMRI611724  PESA16016004    1903       1903
 8  PESA_Brain:PESA16016004:BMRI611724  PESA16016004    1904       1904
 9  PESA_Brain:PESA16016004:BMRI611724  PESA16016004    1905       1905

   series_description quality modality orientation resource_label  \
 0           cs3DI_MC  usable      tof         NaN          DICOM
 1     MIP - cs3DI_MC  usable      tof         NaN          DICOM
 2    RL 4DQflowNeuro  usable   4dflow          RL          DICOM
 3    AP 4DQflowNeuro  usable   4dflow          AP          DICOM
 4    FH 4DQflowNeuro  usable   4dflow          FH          DICOM
 5           cs3DI_MC  usable      tof         NaN          DICOM
 6     MIP - cs3DI_MC  usable      tof         NaN          DICOM
 7    RL 4DQflowNeuro  usable   4dflow          RL          DICOM
 8    AP 4DQflowNeuro  usable   4dflow          AP          DICOM
 9    FH 4DQflowNeuro  usable   4dflow          FH          DICOM

   local_cache_path                                           xnat_uri  \
 0             <NA>  /data/projects/PESA_Brain/subjects/CNIC_S01366...
 1             <NA>  /data/projects/PESA_Brain/subjects/CNIC_S01366...
 2             <NA>  /data/projects/PESA_Brain/subjects/CNIC_S01366...
 3             <NA>  /data/projects/PESA_Brain/subjects/CNIC_S01366...
 4             <NA>  /data/projects/PESA_Brain/subjects/CNIC_S01366...
 5             <NA>  /data/projects/PESA_Brain/subjects/CNIC_S00801...
 6             <NA>  /data/projects/PESA_Brain/subjects/CNIC_S00801...
 7             <NA>  /data/projects/PESA_Brain/subjects/CNIC_S00801...
 8             <NA>  /data/projects/PESA_Brain/subjects/CNIC_S00801...
 9             <NA>  /data/projects/PESA_Brain/subjects/CNIC_S00801...

              source_batch_id                 updated_at
 0  xnat_20260413T092010+0000  2026-04-13T09:20:12+00:00
 1  xnat_20260413T092010+0000  2026-04-13T09:20:12+00:00
 2  xnat_20260413T092010+0000  2026-04-13T09:20:12+00:00
 3  xnat_20260413T092010+0000  2026-04-13T09:20:12+00:00
 4  xnat_20260413T092010+0000  2026-04-13T09:20:12+00:00
 5  xnat_20260413T092010+0000  2026-04-13T09:20:13+00:00
 6  xnat_20260413T092010+0000  2026-04-13T09:20:13+00:00
 7  xnat_20260413T092010+0000  2026-04-13T09:20:13+00:00
 8  xnat_20260413T092010+0000  2026-04-13T09:20:13+00:00
 9  xnat_20260413T092010+0000  2026-04-13T09:20:13+00:00  ,
 'assets': Empty DataFrame
 Columns: []
 Index: []}

In [ ]:
# from nvitk.db import DataRepo, sync_xnat_project

# repo = DataRepo("~/nvitk/dataset", auto_scaffold=True)

# frames = sync_xnat_project(
#     repo,
#     config,
#     subjects=["PESA10407076", "PESA16016004"],          # or None for all subjects in project
#     requested_sequences="TOF,4DFLOW_AP,4DFLOW_FH,4DFLOW_RL",  # optional filter
#     download_root="/data_local/LabVF/PESA-Brain/DATA/BatchTest/DICOM_XNAT_TEST/",      # required for downloads
#     download_dicoms=False,                  # DICOM assets under .../{subject}/{sequence}/
#     download_niftis=False,                  # NIfTI under .../{subject}/{sequence}/nifti/
#     nifti_resource_label="DICOM",
#     nifti_download_root=None,              # None → same base as download_root logic in code
#     skip_existing=False,
#     build_sqlite_index=True,
# )

# # frames["subjects"], frames["sessions"], frames["scans"], frames["assets"] — may be empty if nothing matched
# frames

In [10]:
assets_df = repo.assets(filters={"modality": "4dflow", "asset_type": "nifti"})
assets_df

,asset_uid,subject_uid,session_uid,modality,asset_type,asset_path,resource_label,source,pipeline_name,pipeline_id,exists_locally,metadata_json,source_batch_id,updated_at,asset_slot
0,local:PESA10758400:4dflow:PESA10758400/4DFlow/...,PESA10758400,None,4dflow,nifti,/data_local/LabVF/PESA-Brain/DATA/Nifti/PESA10...,4DFlow/AP,local_nifti,None,raw,True,"{""relative_path"": ""PESA10758400/4DFlow/AP/BMRI...",local_nifti_20260411T150248+0000,2026-04-11T15:02:48+00:00,flow_ap_m
1,local:PESA10758400:4dflow:PESA10758400/4DFlow/...,PESA10758400,None,4dflow,nifti,/data_local/LabVF/PESA-Brain/DATA/Nifti/PESA10...,4DFlow/AP,local_nifti,None,raw,True,"{""relative_path"": ""PESA10758400/4DFlow/AP/BMRI...",local_nifti_20260411T150248+0000,2026-04-11T15:02:48+00:00,flow_ap_ph
2,local:PESA10758400:4dflow:PESA10758400/4DFlow/...,PESA10758400,None,4dflow,nifti,/data_local/LabVF/PESA-Brain/DATA/Nifti/PESA10...,4DFlow,local_nifti,None,raw,True,"{""relative_path"": ""PESA10758400/4DFlow/Angiogr...",local_nifti_20260411T150248+0000,2026-04-11T15:02:48+00:00,flow_angiography_3d
3,local:PESA10758400:4dflow:PESA10758400/4DFlow/...,PESA10758400,None,4dflow,nifti,/data_local/LabVF/PESA-Brain/DATA/Nifti/PESA10...,4DFlow,local_nifti,None,raw,True,"{""relative_path"": ""PESA10758400/4DFlow/Angiogr...",local_nifti_20260411T150248+0000,2026-04-11T15:02:48+00:00,flow_angiography_4d
4,local:PESA10758400:4dflow:PESA10758400/4DFlow/...,PESA10758400,None,4dflow,nifti,/data_local/LabVF/PESA-Brain/DATA/Nifti/PESA10...,4DFlow,local_nifti,None,raw,True,"{""relative_path"": ""PESA10758400/4DFlow/Complex...",local_nifti_20260411T150248+0000,2026-04-11T15:02:48+00:00,flow_complex_difference_3d
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
131,local:PESA9541921:4dflow:PESA9541921/4DFlow/PC...,PESA9541921,None,4dflow,nifti,/data_local/LabVF/PESA-Brain/DATA/Nifti/PESA95...,4DFlow,local_nifti,None,raw,True,"{""relative_path"": ""PESA9541921/4DFlow/PCMRA_no...",local_nifti_20260411T150248+0000,2026-04-11T15:02:48+00:00,<NA>
132,local:PESA9541921:4dflow:PESA9541921/4DFlow/RL...,PESA9541921,None,4dflow,nifti,/data_local/LabVF/PESA-Brain/DATA/Nifti/PESA95...,4DFlow/RL,local_nifti,None,raw,True,"{""relative_path"": ""PESA9541921/4DFlow/RL/BMRI6...",local_nifti_20260411T150248+0000,2026-04-11T15:02:48+00:00,flow_rl_m
133,local:PESA9541921:4dflow:PESA9541921/4DFlow/RL...,PESA9541921,None,4dflow,nifti,/data_local/LabVF/PESA-Brain/DATA/Nifti/PESA95...,4DFlow/RL,local_nifti,None,raw,True,"{""relative_path"": ""PESA9541921/4DFlow/RL/BMRI6...",local_nifti_20260411T150248+0000,2026-04-11T15:02:48+00:00,flow_rl_ph
134,local:PESA9541921:4dflow:PESA9541921/4DFlow/Ve...,PESA9541921,None,4dflow,nifti,/data_local/LabVF/PESA-Brain/DATA/Nifti/PESA95...,4DFlow,local_nifti,None,raw,True,"{""relative_path"": ""PESA9541921/4DFlow/Velocity...",local_nifti_20260411T150248+0000,2026-04-11T15:02:48+00:00,flow_velocity_magnitude_3d
135,local:PESA9541921:4dflow:PESA9541921/4DFlow/Ve...,PESA9541921,None,4dflow,nifti,/data_local/LabVF/PESA-Brain/DATA/Nifti/PESA95...,4DFlow,local_nifti,None,raw,True,"{""relative_path"": ""PESA9541921/4DFlow/Velocity...",local_nifti_20260411T150248+0000,2026-04-11T15:02:48+00:00,flow_velocity_magnitude_4d

In [5]:
repo.get('scans')

,scan_uid,session_uid,subject_uid,scan_id,scan_label,series_description,quality,modality,orientation,resource_label,local_cache_path,xnat_uri,source_batch_id,updated_at
0,PESA_Brain:PESA10407076:BMRI395267:1401,PESA_Brain:PESA10407076:BMRI395267,PESA10407076,1401,1401,cs3DI_MC,usable,tof,<NA>,DICOM,/data_local/LabVF/PESA-Brain/DATA/BatchTest/DI...,/data/projects/PESA_Brain/subjects/CNIC_S01366...,xnat_20260413T084528+0000,2026-04-13T08:45:34+00:00
1,PESA_Brain:PESA10407076:BMRI395267:1402,PESA_Brain:PESA10407076:BMRI395267,PESA10407076,1402,1402,MIP - cs3DI_MC,usable,tof,<NA>,DICOM,/data_local/LabVF/PESA-Brain/DATA/BatchTest/DI...,/data/projects/PESA_Brain/subjects/CNIC_S01366...,xnat_20260413T084528+0000,2026-04-13T08:45:34+00:00
2,PESA_Brain:PESA10407076:BMRI395267:1803,PESA_Brain:PESA10407076:BMRI395267,PESA10407076,1803,1803,RL 4DQflowNeuro,usable,4dflow,RL,DICOM,/data_local/LabVF/PESA-Brain/DATA/BatchTest/DI...,/data/projects/PESA_Brain/subjects/CNIC_S01366...,xnat_20260413T084528+0000,2026-04-13T08:45:43+00:00
3,PESA_Brain:PESA10407076:BMRI395267:1804,PESA_Brain:PESA10407076:BMRI395267,PESA10407076,1804,1804,AP 4DQflowNeuro,usable,4dflow,AP,DICOM,/data_local/LabVF/PESA-Brain/DATA/BatchTest/DI...,/data/projects/PESA_Brain/subjects/CNIC_S01366...,xnat_20260413T084528+0000,2026-04-13T08:45:53+00:00
4,PESA_Brain:PESA10407076:BMRI395267:1805,PESA_Brain:PESA10407076:BMRI395267,PESA10407076,1805,1805,FH 4DQflowNeuro,usable,4dflow,FH,DICOM,/data_local/LabVF/PESA-Brain/DATA/BatchTest/DI...,/data/projects/PESA_Brain/subjects/CNIC_S01366...,xnat_20260413T084528+0000,2026-04-13T08:46:06+00:00
5,PESA_Brain:PESA16016004:BMRI611724:1501,PESA_Brain:PESA16016004:BMRI611724,PESA16016004,1501,1501,cs3DI_MC,usable,tof,<NA>,DICOM,/data_local/LabVF/PESA-Brain/DATA/BatchTest/DI...,/data/projects/PESA_Brain/subjects/CNIC_S00801...,xnat_20260413T084528+0000,2026-04-13T08:46:11+00:00
6,PESA_Brain:PESA16016004:BMRI611724:1502,PESA_Brain:PESA16016004:BMRI611724,PESA16016004,1502,1502,MIP - cs3DI_MC,usable,tof,<NA>,DICOM,/data_local/LabVF/PESA-Brain/DATA/BatchTest/DI...,/data/projects/PESA_Brain/subjects/CNIC_S00801...,xnat_20260413T084528+0000,2026-04-13T08:46:11+00:00
7,PESA_Brain:PESA16016004:BMRI611724:1903,PESA_Brain:PESA16016004:BMRI611724,PESA16016004,1903,1903,RL 4DQflowNeuro,usable,4dflow,RL,DICOM,/data_local/LabVF/PESA-Brain/DATA/BatchTest/DI...,/data/projects/PESA_Brain/subjects/CNIC_S00801...,xnat_20260413T084528+0000,2026-04-13T08:46:20+00:00
8,PESA_Brain:PESA16016004:BMRI611724:1904,PESA_Brain:PESA16016004:BMRI611724,PESA16016004,1904,1904,AP 4DQflowNeuro,usable,4dflow,AP,DICOM,/data_local/LabVF/PESA-Brain/DATA/BatchTest/DI...,/data/projects/PESA_Brain/subjects/CNIC_S00801...,xnat_20260413T084528+0000,2026-04-13T08:46:28+00:00
9,PESA_Brain:PESA16016004:BMRI611724:1905,PESA_Brain:PESA16016004:BMRI611724,PESA16016004,1905,1905,FH 4DQflowNeuro,usable,4dflow,FH,DICOM,/data_local/LabVF/PESA-Brain/DATA/BatchTest/DI...,/data/projects/PESA_Brain/subjects/CNIC_S00801...,xnat_20260413T084528+0000,2026-04-13T08:46:36+00:00

In [9]:
# Same data, explicit filters (column names match the catalog)
assets_df = repo.assets(filters={"modality": "4dflow", "asset_type": "dicom"})
assets_df

,asset_uid,subject_uid,session_uid,modality,asset_type,asset_path,resource_label,source,pipeline_name,pipeline_id,exists_locally,metadata_json,source_batch_id,updated_at,asset_slot
0,PESA_Brain:PESA10407076:BMRI395267:1803:BMRI39...,PESA10407076,PESA_Brain:PESA10407076:BMRI395267,4dflow,dicom,/data_local/LabVF/PESA-Brain/DATA/BatchTest/DI...,DICOM,xnat,None,None,True,{},xnat_20260413T084528+0000,2026-04-13T08:45:43+00:00,<NA>
1,PESA_Brain:PESA10407076:BMRI395267:1803:BMRI39...,PESA10407076,PESA_Brain:PESA10407076:BMRI395267,4dflow,dicom,/data_local/LabVF/PESA-Brain/DATA/BatchTest/DI...,DICOM,xnat,None,None,True,{},xnat_20260413T084528+0000,2026-04-13T08:45:43+00:00,<NA>
2,PESA_Brain:PESA10407076:BMRI395267:1803:BMRI39...,PESA10407076,PESA_Brain:PESA10407076:BMRI395267,4dflow,dicom,/data_local/LabVF/PESA-Brain/DATA/BatchTest/DI...,DICOM,xnat,None,None,True,{},xnat_20260413T084528+0000,2026-04-13T08:45:43+00:00,<NA>
3,PESA_Brain:PESA10407076:BMRI395267:1803:BMRI39...,PESA10407076,PESA_Brain:PESA10407076:BMRI395267,4dflow,dicom,/data_local/LabVF/PESA-Brain/DATA/BatchTest/DI...,DICOM,xnat,None,None,True,{},xnat_20260413T084528+0000,2026-04-13T08:45:43+00:00,<NA>
4,PESA_Brain:PESA10407076:BMRI395267:1803:1.3.46...,PESA10407076,PESA_Brain:PESA10407076:BMRI395267,4dflow,dicom,/data_local/LabVF/PESA-Brain/DATA/BatchTest/DI...,DICOM,xnat,None,None,True,{},xnat_20260413T084528+0000,2026-04-13T08:45:43+00:00,<NA>
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18811,PESA_Brain:PESA16016004:BMRI611724:1905:1.3.46...,PESA16016004,PESA_Brain:PESA16016004:BMRI611724,4dflow,dicom,/data_local/LabVF/PESA-Brain/DATA/BatchTest/DI...,DICOM,xnat,None,None,True,{},xnat_20260413T084528+0000,2026-04-13T08:46:36+00:00,<NA>
18812,PESA_Brain:PESA16016004:BMRI611724:1905:1.3.46...,PESA16016004,PESA_Brain:PESA16016004:BMRI611724,4dflow,dicom,/data_local/LabVF/PESA-Brain/DATA/BatchTest/DI...,DICOM,xnat,None,None,True,{},xnat_20260413T084528+0000,2026-04-13T08:46:36+00:00,<NA>
18813,PESA_Brain:PESA16016004:BMRI611724:1905:1.3.46...,PESA16016004,PESA_Brain:PESA16016004:BMRI611724,4dflow,dicom,/data_local/LabVF/PESA-Brain/DATA/BatchTest/DI...,DICOM,xnat,None,None,True,{},xnat_20260413T084528+0000,2026-04-13T08:46:36+00:00,<NA>
18814,PESA_Brain:PESA16016004:BMRI611724:1905:1.3.46...,PESA16016004,PESA_Brain:PESA16016004:BMRI611724,4dflow,dicom,/data_local/LabVF/PESA-Brain/DATA/BatchTest/DI...,DICOM,xnat,None,None,True,{},xnat_20260413T084528+0000,2026-04-13T08:46:36+00:00,<NA>
18815,PESA_Brain:PESA16016004:BMRI611724:1905:1.3.46...,PESA16016004,PESA_Brain:PESA16016004:BMRI611724,4dflow,dicom,/data_local/LabVF/PESA-Brain/DATA/BatchTest/DI...,DICOM,xnat,None,None,True,{},xnat_20260413T084528+0000,2026-04-13T08:46:36+00:00,<NA>

In [11]:

assets_df = repo.assets(filters={"source": "xnat"})
assets_df

,asset_uid,subject_uid,session_uid,modality,asset_type,asset_path,resource_label,source,pipeline_name,pipeline_id,exists_locally,metadata_json,source_batch_id,updated_at,asset_slot
0,PESA_Brain:PESA10407076:BMRI395267:1401:BMRI39...,PESA10407076,PESA_Brain:PESA10407076:BMRI395267,tof,dicom,/data_local/LabVF/PESA-Brain/DATA/BatchTest/DI...,DICOM,xnat,None,None,True,{},xnat_20260413T084528+0000,2026-04-13T08:45:34+00:00,<NA>
1,PESA_Brain:PESA10407076:BMRI395267:1401:BMRI39...,PESA10407076,PESA_Brain:PESA10407076:BMRI395267,tof,dicom,/data_local/LabVF/PESA-Brain/DATA/BatchTest/DI...,DICOM,xnat,None,None,True,{},xnat_20260413T084528+0000,2026-04-13T08:45:34+00:00,<NA>
2,PESA_Brain:PESA10407076:BMRI395267:1401:1.3.46...,PESA10407076,PESA_Brain:PESA10407076:BMRI395267,tof,dicom,/data_local/LabVF/PESA-Brain/DATA/BatchTest/DI...,DICOM,xnat,None,None,True,{},xnat_20260413T084528+0000,2026-04-13T08:45:34+00:00,<NA>
3,PESA_Brain:PESA10407076:BMRI395267:1401:1.3.46...,PESA10407076,PESA_Brain:PESA10407076:BMRI395267,tof,dicom,/data_local/LabVF/PESA-Brain/DATA/BatchTest/DI...,DICOM,xnat,None,None,True,{},xnat_20260413T084528+0000,2026-04-13T08:45:34+00:00,<NA>
4,PESA_Brain:PESA10407076:BMRI395267:1401:1.3.46...,PESA10407076,PESA_Brain:PESA10407076:BMRI395267,tof,dicom,/data_local/LabVF/PESA-Brain/DATA/BatchTest/DI...,DICOM,xnat,None,None,True,{},xnat_20260413T084528+0000,2026-04-13T08:45:34+00:00,<NA>
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19543,PESA_Brain:PESA16016004:BMRI611724:1905:1.3.46...,PESA16016004,PESA_Brain:PESA16016004:BMRI611724,4dflow,dicom,/data_local/LabVF/PESA-Brain/DATA/BatchTest/DI...,DICOM,xnat,None,None,True,{},xnat_20260413T084528+0000,2026-04-13T08:46:36+00:00,<NA>
19544,PESA_Brain:PESA16016004:BMRI611724:1905:1.3.46...,PESA16016004,PESA_Brain:PESA16016004:BMRI611724,4dflow,dicom,/data_local/LabVF/PESA-Brain/DATA/BatchTest/DI...,DICOM,xnat,None,None,True,{},xnat_20260413T084528+0000,2026-04-13T08:46:36+00:00,<NA>
19545,PESA_Brain:PESA16016004:BMRI611724:1905:1.3.46...,PESA16016004,PESA_Brain:PESA16016004:BMRI611724,4dflow,dicom,/data_local/LabVF/PESA-Brain/DATA/BatchTest/DI...,DICOM,xnat,None,None,True,{},xnat_20260413T084528+0000,2026-04-13T08:46:36+00:00,<NA>
19546,PESA_Brain:PESA16016004:BMRI611724:1905:1.3.46...,PESA16016004,PESA_Brain:PESA16016004:BMRI611724,4dflow,dicom,/data_local/LabVF/PESA-Brain/DATA/BatchTest/DI...,DICOM,xnat,None,None,True,{},xnat_20260413T084528+0000,2026-04-13T08:46:36+00:00,<NA>
19547,PESA_Brain:PESA16016004:BMRI611724:1905:1.3.46...,PESA16016004,PESA_Brain:PESA16016004:BMRI611724,4dflow,dicom,/data_local/LabVF/PESA-Brain/DATA/BatchTest/DI...,DICOM,xnat,None,None,True,{},xnat_20260413T084528+0000,2026-04-13T08:46:36+00:00,<NA>

In [ ]:
from nvitk.db import connect_xnat

with connect_xnat(config) as session:
    project = session.projects[config.project]
    subj = project.subjects["PESA10407076"]
    # ... use pyxnat/xnat API directly